site_name: Preserved
site_url:
site_description: |
  Preserved mod set documentation.
repo_name: Sir-Cow/preserved-wiki
repo_url: https://github.com/Sir-Cow/preserved-wiki
edit_uri: tree/main/docs

nav:
  - Home: index.md
  - Inferno: inferno.md
theme:
  favicon: img/favicon.ico
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference